//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public long Id { get; set; }
        public string Action { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Detail { get; set; }
        public Nullable<long> RecordId { get; set; }
        public string TableName { get; set; }
        public long User_Id { get; set; }
    }
}
