//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuyerRequest()
        {
            this.VendorRequests = new HashSet<VendorRequest>();
        }
    
        public int ID { get; set; }
        public int BuyerID { get; set; }
        public int RequestID { get; set; }
        public int StatusID { get; set; }
        public string BuyerDescription { get; set; }
        public Nullable<double> BuyerPrice { get; set; }
        public Nullable<System.DateTime> QoutationDate { get; set; }
        public Nullable<int> ActionID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual OrderRequest OrderRequest { get; set; }
        public virtual OrderRequestAction OrderRequestAction { get; set; }
        public virtual OrderRequestStatu OrderRequestStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorRequest> VendorRequests { get; set; }
    }
}
