//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderManagementRequest
    {
        public int ID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestStatus { get; set; }
        public int PhoneExtID { get; set; }
        public int DepartmenttID { get; set; }
        public int LocationID { get; set; }
        public int PriorityID { get; set; }
        public int TermOfServiceID { get; set; }
        public int SupervisorID { get; set; }
        public int RequesterID { get; set; }
        public string RequesterComment { get; set; }
        public string SupervisorComment { get; set; }
        public string ManagementComment { get; set; }
        public string RequestTittle { get; set; }
        public string CEOComment { get; set; }
        public int ManagementID { get; set; }
        public int FinalApprovalID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
        public virtual PhoneExt PhoneExt { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual TermsOfService TermsOfService { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
    }
}
