//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequesterRequest
    {
        public int ID { get; set; }
        public int BuyerID { get; set; }
        public int RequestID { get; set; }
        public int ActionID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual OrderRequest OrderRequest { get; set; }
        public virtual OrderRequestAction OrderRequestAction { get; set; }
    }
}
